### ISSUE TITLE
Diagrama de Requisitos y Casos de Uso

### ISSUE THREAD

**Issue by kik548** [kik548/ISO2-2022-C05#1]
Entrega Viernes 28/10/2022.

**Comment by Javi-RC** [comment]
Debido a que nos hemos visto con la necesidad de utilizar el sistema de trabajo colaborativo del Visual Paradigm nuestro tiempo para la realización de esta parte se ha aumentado 1h, ya que hemos tenido que aprender a usarlo.

**Comment by kik548** [comment]
Arreglar fallos de planteamiento para el  5/11/2022
