### ISSUE TITLE
Problema En Visual Paradigm- Commits 

### ISSUE THREAD

**Issue by kik548** [kik548/ISO2-2022-C05#13]
Algunos integrantes del equipo están reportando problemas a la hora de realizar _commits_.

@Javi-RC esta buscando una solución al respecto, reporta si encuentras solución.

- [x] Comprobar que @AitorMillan puede hacer _commits_.
- [x]  Comprobar que @AnaToledano3 puede hacer _commits_.
- [x]  Comprobar que @israelMateos puede hacer _commits_.
- [x]  Comprobar que @AngelLuis1 puede hacer _commits_.

Cuando los 4 integrantes confirmen que pueden hacer commits podremos comprobar si afecta a nuestra #2.

**Comment by Javi-RC** [comment]
El problema ha sido que a la hora de crear el proyecto en Visual Paradigm y crear un grupo de trabajo con todos los integrantes del grupo, solo dos miembros teníamos permisos para poder hacer Read and Commit. Para solucionarlo he hecho lo siguiente:

Desde Visual Paradigm he seleccionado la pestaña de _Team_, posteriormente _Utilities_ y dentro _Open TeamWork Client_.

![image](https://user-images.githubusercontent.com/92325257/201404250-7b57598b-774f-465b-aede-1ad52373ca70.png)


Nos abrirá una pestaña  seleccionaremos _Details_.

![image](https://user-images.githubusercontent.com/92325257/201404563-7d88a037-e60f-4d43-b8f1-c2ba0e7626b4.png)

Al hacer click nos abrirá una página en nuestro navegador, en la cual podremos seleccionar los miembros y editar sus permisos.

![image](https://user-images.githubusercontent.com/92325257/201405406-c83b59c7-e06d-4963-8d8e-17b23529badc.png)

![image](https://user-images.githubusercontent.com/92325257/201406019-77554986-98ec-4560-bbde-e068f93f5d34.png)

![image](https://user-images.githubusercontent.com/92325257/201406864-9b14a033-b0d5-47b3-9172-c606dba61ef6.png)

**Comment by kik548** [comment]
Bien, tras comprobar que este contratiempo no afecta a nuestra planificación podemos continuar con el proyecto.
