### ISSUE TITLE
Planificación del PUD

### ISSUE THREAD

**Issue by kik548** [kik548/ISO2-2022-C05#2]
Comienza tras la finalización del  issue #1.
Finaliza el  Miércoles 2/11/2022.

Están asignados 2 grupos, realizaran 2 planificaciones distintas.

**Comment by AitorMillan** [comment]
Terminado el PUD. @kik548

**Comment by AngelLuis1** [comment]
PUD terminado. @kik548

**Comment by kik548** [comment]
Adaptar la planificación a la  reunión del día 2/11/2022
entrega para el 5/11/2022

**Comment by AitorMillan** [comment]
Subida versión 1.0.0 del PUD @kik548

**Comment by kik548** [comment]
Tenemos que modificarla en base a los requisitos de calidad.

**Comment by AitorMillan** [comment]
Añadida la versión 1.1.0 del PUD @kik548

**Comment by kik548** [comment]
@fgualo.
Ya tenemos la versión de la planificación modificándola con lo que hemos hablado.
Si esta conforme el proyecto puede dar comienzo.

**Comment by fgualo** [comment]
> 

@kik548 por favor indicarme o linkarme aquí donde está la planificación. He revisado la wiki y he visto el acta de gestión de calidad, es solo para validar que se ha añadido el requisito de autenticación de doble factor. En cuanto lo mire, os daré el ok.

**Comment by israelMateos** [comment]
@fgualo
Está en un Excel en la rama iteración-0, [aquí](https://github.com/kik548/ISO2-2022-C05/blob/iteraci%C3%B3n-0/PUD.xlsx). Ya está añadido todo en la wiki también, se nos había olvidado.

**Comment by fgualo** [comment]
ok a la planificación!
